In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd

master_df = pd.read_excel(
    "/content/drive/MyDrive/ADSProject/Project_Root/Merged_Dataset/master_df.xlsx"
)

Data Profiling

In [5]:
print("Shape:", master_df.shape)

print("\n--- Data Types ---")
print(master_df.dtypes)

print("\n--- Missing Values ---")
print(master_df.isnull().sum())

print("\n--- Unique Values ---")
print(master_df.nunique())

print("\n--- Duplicate Rows ---")
print(master_df.duplicated().sum())

print("\n--- Statistical Summary ---")
print(master_df.describe())

Shape: (7043, 56)

--- Data Types ---
Customer ID                           object
Gender                                object
Age                                    int64
Under 30                              object
Senior Citizen                        object
Married                               object
Dependents                            object
Number of Dependents                   int64
Service ID                            object
Quarter_x                             object
Referred a Friend                     object
Number of Referrals                    int64
Tenure in Months                       int64
Offer                                 object
Phone Service                         object
Avg Monthly Long Distance Charges    float64
Multiple Lines                        object
Internet Service                      object
Internet Type                         object
Avg Monthly GB Download                int64
Online Security                       object
Online Backup                         object
Device Protection Plan                object
Premium Tech Support                  object
Streaming TV                          object
Streaming Movies                      object
Streaming Music                       object
Unlimited Data                        object
Contract                              object
Paperless Billing                     object
Payment Method                        object
Monthly Charge                       float64
Total Charges                        float64
Total Refunds                        float64
Total Extra Data Charges               int64
Total Long Distance Charges          float64
Total Revenue                        float64
Status ID                             object
Quarter_y                             object
Satisfaction Score                     int64
Customer Status                       object
Churn Label                           object
Churn Value                            int64
Churn Score                            int64
CLTV                                   int64
Churn Reason                          object
Location ID                           object
Country                               object
State                                 object
City                                  object
Zip Code                               int64
Lat Long                              object
Latitude                             float64
Longitude                            float64
ID                                     int64
Population                             int64
dtype: object

--- Missing Values ---
Customer ID                             0
Gender                                  0
Age                                     0
Under 30                                0
Senior Citizen                          0
Married                                 0
Dependents                              0
Number of Dependents                    0
Service ID                              0
Quarter_x                               0
Referred a Friend                       0
Number of Referrals                     0
Tenure in Months                        0
Offer                                3877
Phone Service                           0
Avg Monthly Long Distance Charges       0
Multiple Lines                          0
Internet Service                        0
Internet Type                        1526
Avg Monthly GB Download                 0
Online Security                         0
Online Backup                           0
Device Protection Plan                  0
Premium Tech Support                    0
Streaming TV                            0
Streaming Movies                        0
Streaming Music                         0
Unlimited Data                          0
Contract                                0
Paperless Billing                       0
Payment Method                          0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Status ID                               0
Quarter_y                               0
Satisfaction Score                      0
Customer Status                         0
Churn Label                             0
Churn Value                             0
Churn Score                             0
CLTV                                    0
Churn Reason                         5174
Location ID                             0
Country                                 0
State                                   0
City                                    0
Zip Code                                0
Lat Long                                0
Latitude                                0
Longitude                               0
ID                                      0
Population                              0
dtype: int64

--- Unique Values ---
Customer ID                          7043
Gender                                  2
Age                                    62
Under 30                                2
Senior Citizen                          2
Married                                 2
Dependents                              2
Number of Dependents                   12
Service ID                           7043
Quarter_x                               1
Referred a Friend                       2
Number of Referrals                    12
Tenure in Months                       72
Offer                                   5
Phone Service                           2
Avg Monthly Long Distance Charges    3584
Multiple Lines                          2
Internet Service                        2
Internet Type                           3
Avg Monthly GB Download                50
Online Security                         2
Online Backup                           2
Device Protection Plan                  2
Premium Tech Support                    2
Streaming TV                            2
Streaming Movies                        2
Streaming Music                         2
Unlimited Data                          2
Contract                                3
Paperless Billing                       2
Payment Method                          3
Monthly Charge                       1585
Total Charges                        6540
Total Refunds                         500
Total Extra Data Charges               16
Total Long Distance Charges          6081
Total Revenue                        6975
Status ID                            7043
Quarter_y                               1
Satisfaction Score                      5
Customer Status                         3
Churn Label                             2
Churn Value                             2
Churn Score                            81
CLTV                                 3438
Churn Reason                           36
Location ID                          7043
Country                                 1
State                                   1
City                                 1111
Zip Code                             1625
Lat Long                             1679
Latitude                             1626
Longitude                            1625
ID                                   1625
Population                           1569
dtype: int64

--- Duplicate Rows ---
0

--- Statistical Summary ---
               Age  Number of Dependents  Number of Referrals  \
count  7043.000000           7043.000000          7043.000000
mean     46.509726              0.468124             1.951867
std      16.750352              0.963521             3.001199
min      19.000000             -2.000000             0.000000
25%      32.000000              0.000000             0.000000
50%      46.000000              0.000000             0.000000
75%      60.000000              0.000000             3.000000
max      80.000000              9.000000            11.000000

       Tenure in Months  Avg Monthly Long Distance Charges  \
count       7043.000000                        7043.000000
mean          32.386767                          22.958954
std           24.542061                          15.448113
min            1.000000                           0.000000
25%            9.000000                           9.210000
50%           29.000000                          22.890000
75%           55.000000                          36.395000
max           72.000000                          49.990000

       Avg Monthly GB Download  Monthly Charge  Total Charges  Total Refunds  \
count              7043.000000     7043.000000    7043.000000    7043.000000
mean                 20.515405       64.761692    2280.381264       1.962182
std                  20.418940       30.090047    2266.220462       7.902614
min                   0.000000       18.250000      18.800000       0.000000
25%                   3.000000       35.500000     400.150000       0.000000
50%                  17.000000       70.350000    1394.550000       0.000000
75%                  27.000000       89.850000    3786.600000       0.000000
max                  85.000000      118.750000    8684.800000      49.790000

       Total Extra Data Charges  ...  Total Revenue  Satisfaction Score  \
count               7043.000000  ...    7043.000000         7043.000000
mean                   6.860713  ...    3034.379056            3.244924
std                   25.104978  ...    2865.204542            1.201657
min                    0.000000  ...      21.360000            1.000000
25%                    0.000000  ...     605.610000            3.000000
50%                    0.000000  ...    2108.640000            3.000000
75%                    0.000000  ...    4801.145000            4.000000
max                  150.000000  ...   11979.340000            5.000000

       Churn Value  Churn Score         CLTV      Zip Code     Latitude  \
count  7043.000000  7043.000000  7043.000000   7043.000000  7043.000000
mean      0.265370    58.505040  4400.295755  93486.071134    36.197455
std       0.441561    21.170031  1183.057152   1856.768045     2.468929
min       0.000000     5.000000  2003.000000  90001.000000    32.555828
25%       0.000000    40.000000  3469.000000  92101.000000    33.990646
50%       0.000000    61.000000  4527.000000  93518.000000    36.205465
75%       1.000000    75.500000  5380.500000  95329.000000    38.161321
max       1.000000    96.000000  6500.000000  96150.000000    41.962127

         Longitude           ID     Population
count  7043.000000  7043.000000    7043.000000
mean   -119.756684   784.801221   22139.814568
std       2.154425   489.044508   21152.174407
min    -124.301372     1.000000      11.000000
25%    -121.788090   353.000000    2344.000000
50%    -119.595293   759.000000   17554.000000
75%    -117.969795  1208.000000   36125.000000
max    -114.192901  1670.000000  105285.000000

[8 rows x 21 columns]

In [6]:
profile = pd.DataFrame({
    "Data Type": master_df.dtypes,
    "Missing Values": master_df.isnull().sum(),
    "Missing %": (master_df.isnull().sum() / len(master_df) * 100).round(2),
    "Unique Values": master_df.nunique()
})

profile

,Data Type,Missing Values,Missing %,Unique Values
Customer ID,object,0,0.00,7043
Gender,object,0,0.00,2
Age,int64,0,0.00,62
Under 30,object,0,0.00,2
Senior Citizen,object,0,0.00,2
Married,object,0,0.00,2
Dependents,object,0,0.00,2
Number of Dependents,int64,0,0.00,12
Service ID,object,0,0.00,7043
Quarter_x,object,0,0.00,1
Referred a Friend,object,0,0.00,2
Number of Referrals,int64,0,0.00,12
Tenure in Months,int64,0,0.00,72
Offer,object,3877,55.05,5
Phone Service,object,0,0.00,2
Avg Monthly Long Distance Charges,float64,0,0.00,3584
Multiple Lines,object,0,0.00,2
Internet Service,object,0,0.00,2
Internet Type,object,1526,21.67,3
Avg Monthly GB Download,int64,0,0.00,50
Online Security,object,0,0.00,2
Online Backup,object,0,0.00,2
Device Protection Plan,object,0,0.00,2
Premium Tech Support,object,0,0.00,2
Streaming TV,object,0,0.00,2
Streaming Movies,object,0,0.00,2
Streaming Music,object,0,0.00,2
Unlimited Data,object,0,0.00,2
Contract,object,0,0.00,3
Paperless Billing,object,0,0.00,2
Payment Method,object,0,0.00,3
Monthly Charge,float64,0,0.00,1585
Total Charges,float64,0,0.00,6540
Total Refunds,float64,0,0.00,500
Total Extra Data Charges,int64,0,0.00,16
Total Long Distance Charges,float64,0,0.00,6081
Total Revenue,float64,0,0.00,6975
Status ID,object,0,0.00,7043
Quarter_y,object,0,0.00,1
Satisfaction Score,int64,0,0.00,5
Customer Status,object,0,0.00,3
Churn Label,object,0,0.00,2
Churn Value,int64,0,0.00,2
Churn Score,int64,0,0.00,81
CLTV,int64,0,0.00,3438
Churn Reason,object,5174,73.46,36
Location ID,object,0,0.00,7043
Country,object,0,0.00,1
State,object,0,0.00,1
City,object,0,0.00,1111
Zip Code,int64,0,0.00,1625
Lat Long,object,0,0.00,1679
Latitude,float64,0,0.00,1626
Longitude,float64,0,0.00,1625
ID,int64,0,0.00,1625
Population,int64,0,0.00,1569

##**Data Cleaning & Preprocessing**

###Understanding Data

In [7]:
print("Dataset Shape\n")
print(master_df.shape)

print("\n Dataset Information\n")
master_df.info()

# print("\n Head\n")
# master_df.head()

Dataset Shape

(7043, 56)

 Dataset Information

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 56 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Customer ID                        7043 non-null   object
 1   Gender                             7043 non-null   object
 2   Age                                7043 non-null   int64
 3   Under 30                           7043 non-null   object
 4   Senior Citizen                     7043 non-null   object
 5   Married                            7043 non-null   object
 6   Dependents                         7043 non-null   object
 7   Number of Dependents               7043 non-null   int64
 8   Service ID                         7043 non-null   object
 9   Quarter_x                          7043 non-null   object
 10  Referred a Friend                  7043 non-null   object
 11  Number of Referrals                7043 non-null   int64
 12  Tenure in Months                   7043 non-null   int64
 13  Offer                              3166 non-null   object
 14  Phone Service                      7043 non-null   object
 15  Avg Monthly Long Distance Charges  7043 non-null   float64
 16  Multiple Lines                     7043 non-null   object
 17  Internet Service                   7043 non-null   object
 18  Internet Type                      5517 non-null   object
 19  Avg Monthly GB Download            7043 non-null   int64
 20  Online Security                    7043 non-null   object
 21  Online Backup                      7043 non-null   object
 22  Device Protection Plan             7043 non-null   object
 23  Premium Tech Support               7043 non-null   object
 24  Streaming TV                       7043 non-null   object
 25  Streaming Movies                   7043 non-null   object
 26  Streaming Music                    7043 non-null   object
 27  Unlimited Data                     7043 non-null   object
 28  Contract                           7043 non-null   object
 29  Paperless Billing                  7043 non-null   object
 30  Payment Method                     7043 non-null   object
 31  Monthly Charge                     7043 non-null   float64
 32  Total Charges                      7043 non-null   float64
 33  Total Refunds                      7043 non-null   float64
 34  Total Extra Data Charges           7043 non-null   int64
 35  Total Long Distance Charges        7043 non-null   float64
 36  Total Revenue                      7043 non-null   float64
 37  Status ID                          7043 non-null   object
 38  Quarter_y                          7043 non-null   object
 39  Satisfaction Score                 7043 non-null   int64
 40  Customer Status                    7043 non-null   object
 41  Churn Label                        7043 non-null   object
 42  Churn Value                        7043 non-null   int64
 43  Churn Score                        7043 non-null   int64
 44  CLTV                               7043 non-null   int64
 45  Churn Reason                       1869 non-null   object
 46  Location ID                        7043 non-null   object
 47  Country                            7043 non-null   object
 48  State                              7043 non-null   object
 49  City                               7043 non-null   object
 50  Zip Code                           7043 non-null   int64
 51  Lat Long                           7043 non-null   object
 52  Latitude                           7043 non-null   float64
 53  Longitude                          7043 non-null   float64
 54  ID                                 7043 non-null   int64
 55  Population                         7043 non-null   int64
dtypes: float64(8), int64(13), object(35)
memory usage: 3.0+ MB

*   7043 rows × 56 columns
*   No missing values in most columns.
*   Numeric columns have correct data types.

**Things to address**

1. Offer → 3166 non-null (3877 missing)
2. Internet Type → 5517 non-null (1526 missing)
3. Churn Reason → 1869 non-null (5174 missing)
4. Quarter_x and Quarter_y (probably duplicate information)
5. Several ID columns (Customer ID, Service ID, Status ID, Location ID, ID) that likely won't be used for model training.

####**Check for Duplicates**

In [8]:

duplicate_rows = master_df.duplicated().sum()
print("Duplicate Rows:", duplicate_rows)

Duplicate Rows: 0

####**Count and calculate percentage of missing values**

In [9]:
missing = pd.DataFrame({
    "Missing Values": master_df.isnull().sum(),
    "Percentage": (master_df.isnull().sum() / len(master_df)) * 100
})

missing = missing[missing["Missing Values"] > 0]
missing.sort_values(by="Missing Values", ascending=False)

               Missing Values  Percentage
Churn Reason             5174   73.463013
Offer                    3877   55.047565
Internet Type            1526   21.666903

In [10]:
# We're investigating whether missing Internet Type is related to:
# Internet Service = No

# It is missing because the customer doesn't have internet service.

master_df[master_df["Internet Type"].isnull()]["Internet Service"].value_counts()

# Check the Internet Service values for customers with missing Internet Type.
# All 1,526 missing Internet Type values belong to customers with no Internet Service.

Internet Service
No    1526
Name: count, dtype: int64

In [11]:
master_df[master_df["Offer"].isnull()]["Customer Status"].value_counts()

Customer Status
Stayed     2547
Churned    1051
Joined      279
Name: count, dtype: int64

In [12]:
# Among customers with a missing Offer, what is their Customer Status?
# Among customers whose Offer is missing, how many are Stayed, Churned, or Joined.
master_df[master_df["Offer"].isnull()]["Customer Status"].value_counts()

Customer Status
Stayed     2547
Churned    1051
Joined      279
Name: count, dtype: int64

In [13]:
# check whether missing Offer is related to Churn Label.
master_df[master_df["Offer"].isnull()]["Churn Label"].value_counts()

Churn Label
No     2826
Yes    1051
Name: count, dtype: int64

In [14]:
# which Offer values exist for customers who actually have an offer.
master_df["Offer"].value_counts(dropna=False)

Offer
NaN        3877
Offer B     824
Offer E     805
Offer D     602
Offer A     520
Offer C     415
Name: count, dtype: int64

In [15]:
master_df[master_df["Offer"].isnull()]["Referred a Friend"].value_counts()

Referred a Friend
No     2119
Yes    1758
Name: count, dtype: int64

In [16]:
master_df[master_df["Offer"].isnull()]["Tenure in Months"].describe()

count    3877.000000
mean       31.566159
std        24.052436
min         1.000000
25%         8.000000
50%        29.000000
75%        53.000000
max        72.000000
Name: Tenure in Months, dtype: float64

In [17]:
master_df[master_df["Offer"].isnull()]["Contract"].value_counts()

Contract
Month-to-Month    2020
Two Year          1015
One Year           842
Name: count, dtype: int64

In [18]:
master_df[master_df["Offer"].isnull()]["Internet Service"].value_counts()

Internet Service
Yes    3024
No      853
Name: count, dtype: int64

In [19]:
pd.crosstab(
    master_df["Customer Status"],
    master_df["Offer"],
    dropna=False
)

Offer            Offer A  Offer B  Offer C  Offer D  Offer E   NaN
Customer Status
Churned               35      101       95      161      426  1051
Joined                 0        0        0        0      175   279
Stayed               485      723      320      441      204  2547

In [20]:
master_df[master_df["Churn Reason"].isnull()]["Customer Status"].value_counts()

Customer Status
Stayed    4720
Joined     454
Name: count, dtype: int64

In [21]:
master_df["Internet Type"] = master_df["Internet Type"].fillna("No Internet")
master_df["Internet Type"].isnull().sum()

np.int64(0)

In [22]:
master_df["Offer"] = master_df["Offer"].fillna("No Offer")
master_df["Offer"].isnull().sum()

np.int64(0)

In [23]:
master_df[master_df["Churn Reason"].isnull()]["Customer Status"].value_counts()

Customer Status
Stayed    4720
Joined     454
Name: count, dtype: int64

In [24]:
master_df["Churn Reason"] = master_df["Churn Reason"].fillna("Not Churned")
master_df["Churn Reason"].isnull().sum()

np.int64(0)

In [25]:
master_df.columns.tolist()

['Customer ID',
 'Gender',
 'Age',
 'Under 30',
 'Senior Citizen',
 'Married',
 'Dependents',
 'Number of Dependents',
 'Service ID',
 'Quarter_x',
 'Referred a Friend',
 'Number of Referrals',
 'Tenure in Months',
 'Offer',
 'Phone Service',
 'Avg Monthly Long Distance Charges',
 'Multiple Lines',
 'Internet Service',
 'Internet Type',
 'Avg Monthly GB Download',
 'Online Security',
 'Online Backup',
 'Device Protection Plan',
 'Premium Tech Support',
 'Streaming TV',
 'Streaming Movies',
 'Streaming Music',
 'Unlimited Data',
 'Contract',
 'Paperless Billing',
 'Payment Method',
 'Monthly Charge',
 'Total Charges',
 'Total Refunds',
 'Total Extra Data Charges',
 'Total Long Distance Charges',
 'Total Revenue',
 'Status ID',
 'Quarter_y',
 'Satisfaction Score',
 'Customer Status',
 'Churn Label',
 'Churn Value',
 'Churn Score',
 'CLTV',
 'Churn Reason',
 'Location ID',
 'Country',
 'State',
 'City',
 'Zip Code',
 'Lat Long',
 'Latitude',
 'Longitude',
 'ID',
 'Population']

In [26]:
master_df["Quarter_x"].equals(master_df["Quarter_y"])

True

In [27]:
master_df = master_df.drop(columns=["Quarter_y"])

In [28]:
print(master_df.columns.tolist())

['Customer ID', 'Gender', 'Age', 'Under 30', 'Senior Citizen', 'Married', 'Dependents', 'Number of Dependents', 'Service ID', 'Quarter_x', 'Referred a Friend', 'Number of Referrals', 'Tenure in Months', 'Offer', 'Phone Service', 'Avg Monthly Long Distance Charges', 'Multiple Lines', 'Internet Service', 'Internet Type', 'Avg Monthly GB Download', 'Online Security', 'Online Backup', 'Device Protection Plan', 'Premium Tech Support', 'Streaming TV', 'Streaming Movies', 'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing', 'Payment Method', 'Monthly Charge', 'Total Charges', 'Total Refunds', 'Total Extra Data Charges', 'Total Long Distance Charges', 'Total Revenue', 'Status ID', 'Satisfaction Score', 'Customer Status', 'Churn Label', 'Churn Value', 'Churn Score', 'CLTV', 'Churn Reason', 'Location ID', 'Country', 'State', 'City', 'Zip Code', 'Lat Long', 'Latitude', 'Longitude', 'ID', 'Population']

In [29]:

master_df = master_df.drop(columns=[
    "Customer ID",
    "Service ID",
    "Status ID",
    "Location ID",
    "ID"
])

In [30]:
print(master_df.shape)

(7043, 50)

In [31]:
constant_cols = [
    col for col in master_df.columns
    if master_df[col].nunique() <= 1
]

print(constant_cols)

['Quarter_x', 'Country', 'State']

In [32]:

master_df = master_df.drop(columns=[
    "Quarter_x",
    "Country",
    "State"
])

In [33]:
master_df.isnull().sum()[master_df.isnull().sum() > 0]

Series([], dtype: int64)

In [34]:
master_df.dtypes.value_counts()

object     27
int64      12
float64     8
Name: count, dtype: int64

In [35]:
for col in master_df.select_dtypes(include="object").columns:
    print("\n", col)
    print(master_df[col].unique())

 Gender
['Male' 'Female']

 Under 30
['No' 'Yes']

 Senior Citizen
['Yes' 'No']

 Married
['No' 'Yes']

 Dependents
['No' 'Yes']

 Referred a Friend
['No' 'Yes']

 Offer
['No Offer' 'Offer E' 'Offer D' 'Offer C' 'Offer B' 'Offer A']

 Phone Service
['No' 'Yes']

 Multiple Lines
['No' 'Yes']

 Internet Service
['Yes' 'No']

 Internet Type
['DSL' 'Fiber Optic' 'Cable' 'No Internet']

 Online Security
['No' 'Yes']

 Online Backup
['No' 'Yes']

 Device Protection Plan
['Yes' 'No']

 Premium Tech Support
['No' 'Yes']

 Streaming TV
['No' 'Yes']

 Streaming Movies
['Yes' 'No']

 Streaming Music
['No' 'Yes']

 Unlimited Data
['No' 'Yes']

 Contract
['Month-to-Month' 'One Year' 'Two Year']

 Paperless Billing
['Yes' 'No']

 Payment Method
['Bank Withdrawal' 'Credit Card' 'Mailed Check']

 Customer Status
['Churned' 'Stayed' 'Joined']

 Churn Label
['Yes' 'No']

 Churn Reason
['Competitor offered more data' 'Competitor made better offer'
 'Limited range of services' 'Extra data charges'
 'Competitor had better devices' "Don't know" 'Service dissatisfaction'
 'Lack of affordable download/upload speed' 'Product dissatisfaction'
 'Long distance charges' 'Poor expertise of online support'
 'Attitude of support person' 'Network reliability'
 'Competitor offered higher download speeds' 'Moved' 'Price too high'
 'Attitude of servicé provider' 'Competitor made better offer @'
 'Attitude of service provider' ' Poor expertise of phone support'
 'Deceased' '& Competitor made better offer'
 'Compètitor made better offer' 'Attitudè of servicé provider'
 'Attitudè of service provider' 'Not Churned' 'Long distance charges$'
 'Poor expertise of phone support' 'Competitr made better offer'
 'Price too hìgh' ' Limited range of services' 'Long dístance charges'
 'Lack of self-service on Website' 'Lack of self-service on Website #'
 ' Price too high' ' Lack of self-service on Website'
 ' Long distance charges']

 City
['Los Angeles' 'Inglewood' 'Whittier' ... 'Jacumba' 'Cardiff Sea'
 'Holtville']

 Lat Long
['34.02381, -118.156582' '34.044271, -118.185237' '34.108833, -118.229715'
 ... '32.649787, -116.2237' '32.741859, -117.090353'
 '32.811001, -115.152865']

####**Clean Churn Reason**

In [36]:
master_df["Churn Reason"] = master_df["Churn Reason"].str.strip()

In [37]:
master_df["Churn Reason"].unique()

array(['Competitor offered more data', 'Competitor made better offer',
       'Limited range of services', 'Extra data charges',
       'Competitor had better devices', "Don't know",
       'Service dissatisfaction',
       'Lack of affordable download/upload speed',
       'Product dissatisfaction', 'Long distance charges',
       'Poor expertise of online support', 'Attitude of support person',
       'Network reliability', 'Competitor offered higher download speeds',
       'Moved', 'Price too high', 'Attitude of servicé provider',
       'Competitor made better offer @', 'Attitude of service provider',
       'Poor expertise of phone support', 'Deceased',
       '& Competitor made better offer', 'Compètitor made better offer',
       'Attitudè of servicé provider', 'Attitudè of service provider',
       'Not Churned', 'Long distance charges$',
       'Competitr made better offer', 'Price too hìgh',
       'Long dístance charges', 'Lack of self-service on Website',
       'Lack of self-service on Website #'], dtype=object)

In [38]:
replacements = {
    "Attitude of servicé provider": "Attitude of service provider",
    "Attitudè of servicé provider": "Attitude of service provider",
    "Attitudè of service provider": "Attitude of service provider",
    "Competitor made better offer @": "Competitor made better offer",
    "& Competitor made better offer": "Competitor made better offer",
    "Compètitor made better offer": "Competitor made better offer",
    "Competitr made better offer": "Competitor made better offer",
    "Long distance charges$": "Long distance charges",
    "Long dístance charges": "Long distance charges",
    "Price too hìgh": "Price too high",
    "Lack of self-service on Website #": "Lack of self-service on Website"
}

master_df["Churn Reason"] = master_df["Churn Reason"].replace(replacements)

In [39]:
master_df["Churn Reason"].unique()

array(['Competitor offered more data', 'Competitor made better offer',
       'Limited range of services', 'Extra data charges',
       'Competitor had better devices', "Don't know",
       'Service dissatisfaction',
       'Lack of affordable download/upload speed',
       'Product dissatisfaction', 'Long distance charges',
       'Poor expertise of online support', 'Attitude of support person',
       'Network reliability', 'Competitor offered higher download speeds',
       'Moved', 'Price too high', 'Attitude of service provider',
       'Poor expertise of phone support', 'Deceased', 'Not Churned',
       'Lack of self-service on Website'], dtype=object)

In [40]:

master_df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,7043.0,46.509726,16.750352,19.000000,32.000000,46.000000,60.000000,80.000000
Number of Dependents,7043.0,0.468124,0.963521,-2.000000,0.000000,0.000000,0.000000,9.000000
Number of Referrals,7043.0,1.951867,3.001199,0.000000,0.000000,0.000000,3.000000,11.000000
Tenure in Months,7043.0,32.386767,24.542061,1.000000,9.000000,29.000000,55.000000,72.000000
Avg Monthly Long Distance Charges,7043.0,22.958954,15.448113,0.000000,9.210000,22.890000,36.395000,49.990000
Avg Monthly GB Download,7043.0,20.515405,20.418940,0.000000,3.000000,17.000000,27.000000,85.000000
Monthly Charge,7043.0,64.761692,30.090047,18.250000,35.500000,70.350000,89.850000,118.750000
Total Charges,7043.0,2280.381264,2266.220462,18.800000,400.150000,1394.550000,3786.600000,8684.800000
Total Refunds,7043.0,1.962182,7.902614,0.000000,0.000000,0.000000,0.000000,49.790000
Total Extra Data Charges,7043.0,6.860713,25.104978,0.000000,0.000000,0.000000,0.000000,150.000000
Total Long Distance Charges,7043.0,749.099262,846.660055,0.000000,70.545000,401.440000,1191.100000,3564.720000
Total Revenue,7043.0,3034.379056,2865.204542,21.360000,605.610000,2108.640000,4801.145000,11979.340000
Satisfaction Score,7043.0,3.244924,1.201657,1.000000,3.000000,3.000000,4.000000,5.000000
Churn Value,7043.0,0.265370,0.441561,0.000000,0.000000,0.000000,1.000000,1.000000
Churn Score,7043.0,58.505040,21.170031,5.000000,40.000000,61.000000,75.500000,96.000000
CLTV,7043.0,4400.295755,1183.057152,2003.000000,3469.000000,4527.000000,5380.500000,6500.000000
Zip Code,7043.0,93486.071134,1856.768045,90001.000000,92101.000000,93518.000000,95329.000000,96150.000000
Latitude,7043.0,36.197455,2.468929,32.555828,33.990646,36.205465,38.161321,41.962127
Longitude,7043.0,-119.756684,2.154425,-124.301372,-121.788090,-119.595293,-117.969795,-114.192901
Population,7043.0,22139.814568,21152.174407,11.000000,2344.000000,17554.000000,36125.000000,105285.000000

In [41]:
master_df[master_df["Number of Dependents"] < 0][["Number of Dependents"]]

     Number of Dependents
18                     -1
32                     -1
122                    -2

In [42]:
master_df.loc[
    master_df["Number of Dependents"] < 0,
    "Number of Dependents"
] = 0

In [43]:
master_df["Number of Dependents"].min()

0

In [44]:
numeric_cols = master_df.select_dtypes(include="number").columns

master_df[numeric_cols].lt(0).sum()

Age                                     0
Number of Dependents                    0
Number of Referrals                     0
Tenure in Months                        0
Avg Monthly Long Distance Charges       0
Avg Monthly GB Download                 0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Satisfaction Score                      0
Churn Value                             0
Churn Score                             0
CLTV                                    0
Zip Code                                0
Latitude                                0
Longitude                            7043
Population                              0
dtype: int64

In [45]:
master_df.duplicated().sum()

np.int64(0)

####**Ensure Data is Cleaned**

In [46]:
print("Shape:", master_df.shape)
print("Duplicate rows:", master_df.duplicated().sum())
print("Missing values:", master_df.isnull().sum().sum())

# Check negative values in numeric columns
numeric_cols = master_df.select_dtypes(include="number").columns
print("Negative values:")
print(master_df[numeric_cols].lt(0).sum())

# Check constant columns
constant_cols = [
    col for col in master_df.columns
    if master_df[col].nunique() <= 1
]
print("Constant columns:", constant_cols)

Shape: (7043, 47)
Duplicate rows: 0
Missing values: 0
Negative values:
Age                                     0
Number of Dependents                    0
Number of Referrals                     0
Tenure in Months                        0
Avg Monthly Long Distance Charges       0
Avg Monthly GB Download                 0
Monthly Charge                          0
Total Charges                           0
Total Refunds                           0
Total Extra Data Charges                0
Total Long Distance Charges             0
Total Revenue                           0
Satisfaction Score                      0
Churn Value                             0
Churn Score                             0
CLTV                                    0
Zip Code                                0
Latitude                                0
Longitude                            7043
Population                              0
dtype: int64
Constant columns: []

##**Save Updated Dataset**

In [49]:
# import os

# os.makedirs("/content/Telecom-Customer-Churn-Prediction/data", exist_ok=True)

# master_df.to_csv(
#     "/content/Telecom-Customer-Churn-Prediction/data/master_df.csv",
#     index=False
# )

import os

# Define your target folder and filename
folder_path = '/content/drive/MyDrive/ADSProject/Project_Root/Merged_Dataset'
file_name = 'master_df.csv'
full_path = os.path.join(folder_path, file_name)


# Save the DataFrame to Google Drive
master_df.to_csv(full_path, index=False)

In [50]:
print(os.path.exists(
    "/content/drive/MyDrive/ADSProject/Project_Root/Merged_Dataset/master_df.csv"
))

True